export const LIST_HE_THONG_RAP_REQUEST =
  "ListHeThongRapReducer/LIST_HE_THONG_RAP_REQUEST";
export const LIST_HE_THONG_RAP_SUCCESS =
  "ListHeThongRapReducer/LIST_HE_THONG_RAP_SUCCESS";
export const LIST_HE_THONG_RAP_FAILED =
  "ListHeThongRapReducer/LIST_HE_THONG_RAP_FAILED";

export const LAY_THONG_TIN_LICH_CHIEU_REQUEST =
  "ListHeThongRapReducer/LAY_THONG_TIN_LICH_CHIEU_REQUEST";
export const LAY_THONG_TIN_LICH_CHIEU_SUCCESS =
  "ListHeThongRapReducer/LAY_THONG_TIN_LICH_CHIEU_SUCCESS";
export const LAY_THONG_TIN_LICH_CHIEU_FAILED =
  "ListHeThongRapReducer/LAY_THONG_TIN_LICH_CHIEU_FAILED";
